---
title: "Estudio Microarrays Psoriasis"
author: "Dani Ibañez"
date: "6/3/2021"
output: html_document
---



### PREGUNTA 1: Ejemplo Estudio Microarrays

<br>

#### **Título del Estudio**

Combined Use of Laser Capture Microdissection and cDNA Microarray Analysis Identifies Locally Expressed Disease-Related Genes in Focal Regions of Psoriasis Vulgaris Skin Lesions

<br>

#### **Tipo de Microarrays**

Affymetrix HGU133A 2.0

The GeneChip™ Human Genome U133A 2.0 Array is a **single array** representing **14,500 well-characterized human genes** that can be used to explore human biology and disease processes.

<br>

#### **Número de muestras y grupos**

Paired lesional and non-lesional samples from 7 psoriatic patients were used.
Samples from the first four patients were used in the single vs. double amplification comparison.
Samples from the remaining three patients were subjected to LCM.
NOTA: dos métodos de visualización de muestras de 7 pacientes.

<br>

#### **Objetivo del estudio** 

La psoriasis vulgar es una enfermedad compleja caracterizada por alteraciones en el crecimiento y diferenciación de los queratinocitos epidérmicos, así como un marcado aumento de las poblaciones de leucocitos.

En este estudio, se utiliza microdisección por captura láser (LCM) y análisis de matriz de genes para estudiar la expresión génica de las células en la epidermis y dermis lesionadas, en comparación con las regiones no lesionadas correspondientes. 

Usando este enfoque, se detectan 1800 productos génicos expresados de forma diferencial en la epidermis o dermis de las zonas con psoriasis. En concreto este estudio detectó una producción local de CCL19, una quimiocina organizadora linfoide, y su receptor CCR7 en agregados dérmicos psoriásicos, junto con la presencia de productos génicos LAMP3 / DC-LAMP y CD83, que tipifican las CD maduras.

En conclusión, los patrones de expresión génica obtenidos con LCM y análisis de microarrays junto con la detección de células T y DC mediante tinción inmune sugieren un posible mecanismo para la organización linfoide a través de CCL19 / CCR7 en la piel enferma.

<br>

#### **Enlace de datos y artículo**

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3352975/

Gene Expression Omnibus repository (**GSE26866**)  

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE26866

